FROM centos:centos7

RUN yum update -y

RUN yum install -y git wget java-1.8.0-openjdk.x86_64 java-1.8.0-openjdk-devel.x86_64

RUN curl https://bintray.com/sbt/rpm/rpm | tee /etc/yum.repos.d/bintray-sbt-rpm.repo
RUN yum install sbt -y

RUN cd /etc/sbt && git clone -b develop https://github.com/msuzuki83/ichienyado.git

#WORKDIR /etc/sbt/ichienyado/webapp
#ENTRYPOINT ["sbt", "start"]

WORKDIR /root
ENTRYPOINT ["/bin/sh", "-c", "while true; do echo hello world; sleep 1; done"]
