FROM centos:centos7

RUN yum update -y

RUN yum install -y git wget java-1.8.0-openjdk.x86_64 java-1.8.0-openjdk-devel.x86_64

RUN wget http://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.tgz
RUN tar -xzvf scala-2.11.7.tgz
RUN rm -rf scala-2.11.7.tgz
RUN echo "export SCALA_HOME=/home/ec2-user/scala-2.11.7" >> ~/.bashrc
RUN echo "export PATH=$PATH:/home/ec2-user/scala-2.11.7/bin" >> ~/.bashrc
RUN source ~/.bashrc

RUN curl https://bintray.com/sbt/rpm/rpm | tee /etc/yum.repos.d/bintray-sbt-rpm.repo
RUN yum install sbt -y

RUN cd /etc/sbt && git clone -b develop https://github.com/msuzuki83/ichienyado.git

RUN cd /etc/sbt/ichienyado/webapp/ && sbt run

WORKDIR /root
ENTRYPOINT ["/bin/sh", "-c", "while true; do echo hello world; sleep 1; done"]
