version: '2'

services:
  ichienyado:
    build:
      context: .
      dockerfile: Dockerfile_local
    ports:
      - "80:9000"
    volumes:
      - ${ICHIENYADO_VOLUME_PATH}:/etc/sbt/ichienyado:z
