FROM amazonlinux:2017.09.0.20170930

# init
RUN yum update -y

# install
RUN yum install --enablerepo=epel -y mysql56-server git wget

# settings
RUN chown -R apache:apache /var/www
RUN chmod 2775 /var/www
RUN find /var/www -type d -exec chmod 2775 {} \;
RUN find /var/www -type f -exec chmod 0664 {} \;
RUN echo "NETWORKING=yes" >/etc/sysconfig/network
RUN sed -i -e "151s/None/All/" /etc/httpd/conf/httpd.conf

# start
CMD ["/usr/bin/supervisord", "-n"]
